<Project Sdk="Microsoft.NET.Sdk.WebAssembly">
  <PropertyGroup>
    <TargetFramework>net10.0-browser</TargetFramework>
    <OutputType>Exe</OutputType>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <Nullable>enable</Nullable>
    <UserSecretsId>46623f7d-a960-4655-bf47-ca5a085816ce</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia.Browser" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\UnifyDemo.App\UnifyDemo.App.csproj" />
  </ItemGroup>
</Project>
