<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFrameworks>$(UnifyTargetFrameworks)</TargetFrameworks>
		<Platforms>$(UnifyTargetPlatforms)</Platforms>
	</PropertyGroup>
	
	<PropertyGroup>
		<RootNamespace>CNCO.$(MSBuildProjectName.Replace(" ", "_"))</RootNamespace>
		<SingleProject>true</SingleProject>
		<ImplicitUsings>enable</ImplicitUsings>
		<AllowUnsafeBlocks>true</AllowUnsafeBlocks>
	</PropertyGroup>

	<!-- Windows Toast Notifications -->
	<PropertyGroup Condition="'$(TargetFramework)' == '$(UnifyWindowsTargetFramework)'">
		<DefineConstants>WINDOWS_TOAST_NOTIFICATIONS</DefineConstants>
	</PropertyGroup>

	<ItemGroup Condition="'$(TargetFramework)' == '$(UnifyWindowsTargetFramework)'">
		<PackageReference Include="Microsoft.Toolkit.Uwp.Notifications" Version="7.1.3" />
	</ItemGroup>

	<ItemGroup>
		<Folder Include="Platforms\Android\" />
		<Folder Include="Platforms\iOS\" />
		<Folder Include="Platforms\MacCatalyst\" />
	</ItemGroup>

	<ItemGroup>
		<!-- For NotificationImages -->
		<PackageReference Include="SkiaSharp" Version="3.119.1" />
		<PackageReference Include="SkiaSharp.NativeAssets.WebAssembly" Version="3.119.1" />
	</ItemGroup>
	
	<ItemGroup>
		<ProjectReference Include="..\Unify\Unify.csproj" />
	</ItemGroup>
</Project>
