<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFramework>$(UnifyIosTargetFramework)</TargetFramework>
		<Platforms>$(UnifyTargetPlatforms)</Platforms>
		<OutputType>Exe</OutputType>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Avalonia.iOS" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\UnifyDemo.App\UnifyDemo.App.csproj" />
	</ItemGroup>
</Project>
