<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFrameworks>$(UnifyTargetFrameworks)</TargetFrameworks>
        <Platforms>$(UnifyTargetPlatforms)</Platforms>
    </PropertyGroup>
    <PropertyGroup>
        <RootNamespace>CNCO.$(MSBuildProjectName.Replace(" ", "_"))</RootNamespace>
        <SingleProject>true</SingleProject>
        <ImplicitUsings>enable</ImplicitUsings>
    </PropertyGroup>
    <ItemGroup>
      <PackageReference Include="System.Diagnostics.PerformanceCounter" Version="10.0.11" />
    </ItemGroup>
    <ItemGroup>
      <ProjectReference Include="..\Unify\Unify.csproj" />
    </ItemGroup>

</Project>
