<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFrameworks>$(UnifyTargetFrameworks)</TargetFrameworks>
		<Platforms>$(UnifyTargetPlatforms)</Platforms>

		<AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
	</PropertyGroup>

	<ItemGroup>
	  <AvaloniaResource Include="Assets\**" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Avalonia" />
		<PackageReference Include="Avalonia.Themes.Fluent" />
		<PackageReference Include="Avalonia.Fonts.Inter" />
		<PackageReference Include="Avalonia.Diagnostics">
			<IncludeAssets Condition="'$(Configuration)' != 'Debug'">None</IncludeAssets>
			<PrivateAssets Condition="'$(Configuration)' != 'Debug'">All</PrivateAssets>
		</PackageReference>
		<PackageReference Include="CommunityToolkit.Mvvm" />
	</ItemGroup>

	<ItemGroup>
	<ProjectReference Include="..\..\..\src\Unify.Communications\Unify.Communications.csproj" />
	<ProjectReference Include="..\..\..\src\Unify.Notifications\Unify.Notifications.csproj" />
	<ProjectReference Include="..\..\..\src\Unify\Unify.csproj" />
	</ItemGroup>
</Project>
